import About from "../components/About/About";
import FAQ from "../components/FAQ/FAQ";
import Products from "../components/Products/Products";
import ToggleTop from "../components/ToggleTop/ToggleTop";
import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/index.module.css";
import { Waypoint } from "react-waypoint";
import { useState } from "react";
import HomeLayout from "../components/HomeLayout/HomeLayout";

export default function Home() {
  const router = useRouter();
  const [isShow, setIsShow] = useState(false);

  return (
    <HomeLayout>
      <Head>
        <title>member next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.landing}>
          <h1>Member Panel</h1>
          <Waypoint
            onLeave={() => setIsShow(true)}
            onEnter={() => setIsShow(false)}
          />
          <h4 className={`${styles.animatedH4}`}>
            <span>Experience </span>
            <span>Your </span>
            <span>Dream </span>
            <span>With </span>
            <span>Us</span>
          </h4>
        </div>
        <div className={`${styles.cloudyPicture}`}></div>
        <button onClick={() => router.push("/dashboard")}>dashboard</button>
        <button onClick={() => router.push("/admin/users")}>admin</button>
        <Products />
        <About />
        <FAQ />
        <Waypoint
          onEnter={() => setIsShow(false)}
          onLeave={() => setIsShow(true)}
        />
        <ToggleTop isShow={isShow} />
      </main>
    </HomeLayout>
  );
}
