import About from "../src/components/About/About";
import FAQ from "../src/components/FAQ/FAQ";
import Products from "../src/components/Products/Products";
import ToggleTop from "../src/components/ToggleTop/ToggleTop";
import Head from "next/head";
// import Header from "../components/Header/Header";
// import Footer from "../components/Footer/Footer";
import { useRouter } from "next/router";
// import Image from 'next/image'
import { Inter } from "@next/font/google";
import styles from "../styles/index.module.css";
import { Waypoint } from "react-waypoint";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const [isShow, setIsShow] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.landing}>
          <h1>Member Panel</h1>
          <Waypoint
            onLeave={() => setIsShow(true)}
            onEnter={() => setIsShow(false)}
          />
          <h4 className={`${styles.animatedH4}`}>
            <span>Experience </span>
            <span>Your </span>
            <span>Dream </span>
            <span>With </span>
            <span>Us</span>
          </h4>
        </div>
        <button onClick={() => router.push("/dashboard")}>dashboard</button>
        <Products />
        <About />
        <FAQ />
        <Waypoint
          onEnter={() => setIsShow(false)}
          onLeave={() => setIsShow(true)}
        />
        <ToggleTop isShow={isShow} />
      </main>
    </>
  );
}
